sonar.projectKey=tsonaruser_python-sonar-test
sonar.organization=tsonaruser

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.11
sonar.test.inclusions=tests/**/*.py
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
